[REG-73] [ADD] set logo and background for hotel
TheRegencyGroup/theregencygroup16 pull request #131
Opened 2022-10-31 21:55 UTC by RosSinch

2022-10-31 22:03 UTC, artemShelest requested changes

2022-10-31 22:03 UTC, artemShelest commented on addons/regency_shopsite/static/src/js/frontend/header/store.js
> +            if (this.isNoActiveHotel) {
Do not use negation in boolean names. `this.isActiveHotel` is better than `!this.isNoActiveHotel`

2022-10-31 22:03 UTC, artemShelest commented on addons/regency_shopsite/models/res_partner.py
> +    def _get_background_url(self):
Use uniform compute method naming (`_compute_` prefix)

2022-11-01 08:37 UTC, romanesent commented on addons/regency_shopsite/static/src/js/frontend/header/store.js
> +            document.querySelector('.regency-top').style = cssRec
you need to change a specific style value, for example document.querySelector('.regency-top').style.background

2022-11-01 11:43 UTC, romanesent commented on addons/regency_shopsite/models/website.py
> +
remove

2022-11-02 07:23 UTC, merged