Reg 128 add fees to price sheet product line
TheRegencyGroup/theregencygroup16 pull request #192
Opened 2022-11-09 09:32 UTC by OksanaYeroshenko

2022-11-09 10:13 UTC, edison12347 requested changes

2022-11-09 10:13 UTC, edison12347 commented on addons/regency_estimate/models/fee_value.py
> +    fee_type_id = fields.Many2one('fee.type')
can it be without type? if no, make it required

2022-11-09 10:13 UTC, edison12347 commented on addons/regency_estimate/models/fee_value.py
> +class FeeValue(models.Model):
add _description

2022-11-09 10:13 UTC, edison12347 commented on addons/regency_estimate/models/fee_type.py
> +    _name = 'fee.type'
add _description

2022-11-09 10:13 UTC, edison12347 commented on addons/regency_estimate/models/fee_type.py
> +    product_id = fields.Many2one('product.product', domain="[('detailed_type', '=', 'service')]")
add one2many field for fee value

2022-11-09 10:13 UTC, edison12347 commented on addons/regency_estimate/models/fee_type.py
> +    product_id = fields.Many2one('product.product', domain="[('detailed_type', '=', 'service')]")
is it required?

2022-11-09 10:13 UTC, edison12347 commented on addons/regency_estimate/models/fee_value.py
> +    fee_type_id = fields.Many2one('fee.type')
Think if any other field would be required here

2022-11-09 10:13 UTC, edison12347 commented on addons/regency_estimate/models/product_price_sheet.py
> +    @api.depends('fee_value_ids', 'fee_value_ids.value', 'fee')
missing price and min_qty

2022-11-09 10:13 UTC, edison12347 commented on addons/regency_estimate/views/fee_value.xml
> +                <field name="value"/>
It seems that either value or percent is required

2022-11-09 11:57 UTC, artemShelest commented on addons/regency_estimate/models/product_price_sheet.py
> +    @api.depends('fee_value_ids', 'fee_value_ids.value', 'fee', 'price', 'min_quantity')
'fee_value_ids', 'fee_value_ids.value' dependencies are not needed here.

2022-11-10 08:13 UTC, chupaSV requested changes

2022-11-10 08:26 UTC, edison12347 requested changes

2022-11-10 08:26 UTC, edison12347 commented on addons/regency_estimate/models/fee_type.py
> +    _description = 'Set additional fee types for setting additional fee values for price sheet lines'
_description - should be short - **Fee type** - this is how model will be named
adjust other _description as well

2022-11-10 09:27 UTC, chupaSV approved these changes

2022-11-10 09:28 UTC, edison12347 approved these changes

2022-11-10 11:51 UTC, merged