[REG-467] MASTER [ADD] add pop up with reason for po cancellation
TheRegencyGroup/theregencygroup16 pull request #358
Opened 2022-12-08 23:04 UTC by romadjan

2022-12-08 23:24 UTC, artemShelest requested changes

2022-12-08 23:24 UTC, artemShelest commented on addons/regency_estimate/__manifest__.py
> +        'wizard/cancellation_purcase_order.xml',
Fix typo.

2022-12-09 12:24 UTC, chupaSV approved these changes

2022-12-12 21:32 UTC, artemShelest requested changes

2022-12-12 21:32 UTC, artemShelest commented on addons/regency_estimate/models/purchase_order.py
> +from odoo import fields, models, api, _
Please, do not use translations. Either all strings should be translated or none of them.

2022-12-12 23:45 UTC, artemShelest approved these changes

2022-12-12 23:49 UTC, merged