[REG-568] MASTER [FIX] default customer contact type
TheRegencyGroup/theregencygroup16 pull request #461
Opened 2022-12-24 17:54 UTC by romadjan

2022-12-26 17:54 UTC, artemShelest requested changes

2022-12-26 17:54 UTC, artemShelest commented on addons/regency_estimate/models/res_partner.py
> +from odoo import models, fields, api
Looks like this change is not needed.

2022-12-26 17:54 UTC, artemShelest commented on addons/consumption_agreement/views/consumption_agreement.xml
> +                                             'contact_type': 'customer',
Should it be 'default_contact_type'?

2022-12-26 18:08 UTC, artemShelest approved these changes

2022-12-27 08:38 UTC, chupaSV approved these changes

2022-12-27 14:29 UTC, merged