[REG-567] MASTER [FIX] purchase requisition error on cancel
TheRegencyGroup/theregencygroup16 pull request #470
Opened 2022-12-27 12:14 UTC by romadjan

2022-12-27 12:17 UTC, artemShelest submitted a review, later dismissed

2022-12-27 17:54 UTC, chupaSV requested changes

2022-12-27 17:54 UTC, chupaSV commented on addons/regency_estimate/models/purchase_order.py
>          self.ensure_one()
Should be first line in the method

2022-12-28 08:40 UTC, chupaSV approved these changes

2022-12-28 18:24 UTC, merged