[REG-681][REF]bug on validating the Delivery order
TheRegencyGroup/theregencygroup16 pull request #529
Opened 2023-01-12 14:25 UTC by OksanaYeroshenko

2023-01-12 14:31 UTC, chupaSV submitted a review, later dismissed

2023-01-12 15:47 UTC, artemShelest requested changes

2023-01-12 15:47 UTC, artemShelest commented on addons/regency_estimate/models/delivery_carrier.py
> +            res = res + [{'exact_price': p.carrier_id.fixed_price,
Use append. + on list will create new unnecessary object.

2023-01-13 08:32 UTC, artemShelest approved these changes

2023-01-13 09:28 UTC, merged