[REG-653] master [ADD]  define qty to order from ca
TheRegencyGroup/theregencygroup16 pull request #546
Opened 2023-01-16 08:30 UTC by romadjan

2023-01-16 08:43 UTC, chupaSV requested changes

2023-01-16 08:43 UTC, chupaSV commented on addons/regency_shopsite/models/product_pricelist_item.py
> +
Add a comment that it is an overriding of the core method.

2023-01-16 08:43 UTC, chupaSV commented on addons/regency_shopsite/models/product_pricelist_item.py
> +                elif self.overlay_tmpl_id and self.overlay_tmpl_id in product.overlay_template_ids:
Add comments before starting the custom code and after the code.  E.g:
`# START OF CUSTOM CODE`
`# END OF CUSTOM CODE`

2023-01-16 09:13 UTC, artemShelest requested changes

2023-01-16 09:13 UTC, artemShelest commented on addons/consumption_agreement/models/consumption_agreement.py
> +                    if hide:
`order.hide_create_so_button = not hide`

2023-01-16 09:13 UTC, artemShelest commented on addons/consumption_agreement/static/src/js/consumption_agreement_portal.js
> +            console.log( $target.closest('tr').find('.js_agreement_line_quantity').val(data.agreement_line_id))
Handle errors from the controller (when it returns False). Better change False to something readable and meaningful.
Same for the _callUpdateLineRoute() call below.

2023-01-18 08:31 UTC, chupaSV approved these changes

2023-01-18 10:14 UTC, artemShelest approved these changes

2023-01-18 10:17 UTC, merged