[REG-653] master [FIX] hide create so button on portal if remaining qty on all ca lines equal to 0
TheRegencyGroup/theregencygroup16 pull request #572
Opened 2023-01-19 19:26 UTC by romadjan

2023-01-19 21:33 UTC, artemShelest requested changes

2023-01-19 21:33 UTC, artemShelest commented on addons/consumption_agreement/views/consumption_agreement_portal.xml
> +                        <t t-if="consumption.state == 'confirmed' and consumption.hide_create_so_button == False">
Use negation instead of == False.

2023-01-20 16:21 UTC, chupaSV approved these changes

2023-01-22 10:50 UTC, artemShelest approved these changes

2023-01-22 21:07 UTC, merged